name: "Release"

# These jobs can be tested with nektos/act tool
# https://github.com/nektos/act
#
# Look for "!env.ACT" in the DRY_RUN expression below

on:
  push:
    tags:
      - '**'

env:
  DOCKER_IMAGE: crusttech/grafana
  NODE_VERSION: 16
  GO_VERSION: 1.19

jobs:
  build:
    name: "Build grafana"
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        if: ${{ !env.ACT }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with: { go-version: "${{ env.GO_VERSION }}" }
      - name: Setup YARN
        run: npm install -g yarn @vue/cli-service
      - name: Build image
        if: ${{ !env.ACT }}
        run: make build-docker-full
      - name: Retag image
        if: ${{ !env.ACT }}
        run: |
          docker tag grafana/grafana:dev ghcr.io/crusttech/grafana:${{ env.DOCKER_IMAGE_TAG }}
      - name: Push image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/crusttech/grafana:${{ env.DOCKER_IMAGE_TAG }}
      - name: Setup upterm session
        if: always()
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: petergrlica
